// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleProto.proto

package com.levi.yoon.proto;

public interface SampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.sample.SampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
