// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchRequest.proto

package com.levi.yoon.proto;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.sample.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *쿼리 문자열
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <pre>
   *쿼리 문자열
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <code>int32 result_per_page = 3;</code>
   * @return The resultPerPage.
   */
  int getResultPerPage();

  /**
   * <code>.grpc.sample.Corpus corpus = 4;</code>
   * @return The enum numeric value on the wire for corpus.
   */
  int getCorpusValue();
  /**
   * <code>.grpc.sample.Corpus corpus = 4;</code>
   * @return The corpus.
   */
  com.levi.yoon.proto.Corpus getCorpus();
}
