// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchResult.proto

package com.levi.yoon.proto;

public interface SearchResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.sample.SearchResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
