// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchRequest.proto

package com.levi.yoon.proto;

/**
 * <pre>
 *검색 요청을 위한 요청 객체를 표현하는 message 정의
 * </pre>
 *
 * Protobuf type {@code grpc.sample.SearchRequest}
 */
public  final class SearchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.sample.SearchRequest)
    SearchRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchRequest.newBuilder() to construct.
  private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchRequest() {
    query_ = "";
    corpus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            query_ = s;
            break;
          }
          case 16: {

            pageNumber_ = input.readInt32();
            break;
          }
          case 24: {

            resultPerPage_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            corpus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.levi.yoon.proto.SearchProto.internal_static_grpc_sample_SearchRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.levi.yoon.proto.SearchProto.internal_static_grpc_sample_SearchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.levi.yoon.proto.SearchRequest.class, com.levi.yoon.proto.SearchRequest.Builder.class);
  }

  public static final int QUERY_FIELD_NUMBER = 1;
  private volatile java.lang.Object query_;
  /**
   * <pre>
   *쿼리 문자열
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The query.
   */
  public java.lang.String getQuery() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      query_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *쿼리 문자열
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  public com.google.protobuf.ByteString
      getQueryBytes() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      query_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
  private int pageNumber_;
  /**
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  public int getPageNumber() {
    return pageNumber_;
  }

  public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
  private int resultPerPage_;
  /**
   * <code>int32 result_per_page = 3;</code>
   * @return The resultPerPage.
   */
  public int getResultPerPage() {
    return resultPerPage_;
  }

  public static final int CORPUS_FIELD_NUMBER = 4;
  private int corpus_;
  /**
   * <code>.grpc.sample.Corpus corpus = 4;</code>
   * @return The enum numeric value on the wire for corpus.
   */
  public int getCorpusValue() {
    return corpus_;
  }
  /**
   * <code>.grpc.sample.Corpus corpus = 4;</code>
   * @return The corpus.
   */
  public com.levi.yoon.proto.Corpus getCorpus() {
    @SuppressWarnings("deprecation")
    com.levi.yoon.proto.Corpus result = com.levi.yoon.proto.Corpus.valueOf(corpus_);
    return result == null ? com.levi.yoon.proto.Corpus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getQueryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
    }
    if (pageNumber_ != 0) {
      output.writeInt32(2, pageNumber_);
    }
    if (resultPerPage_ != 0) {
      output.writeInt32(3, resultPerPage_);
    }
    if (corpus_ != com.levi.yoon.proto.Corpus.UNIVERSAL.getNumber()) {
      output.writeEnum(4, corpus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getQueryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
    }
    if (pageNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageNumber_);
    }
    if (resultPerPage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, resultPerPage_);
    }
    if (corpus_ != com.levi.yoon.proto.Corpus.UNIVERSAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, corpus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.levi.yoon.proto.SearchRequest)) {
      return super.equals(obj);
    }
    com.levi.yoon.proto.SearchRequest other = (com.levi.yoon.proto.SearchRequest) obj;

    if (!getQuery()
        .equals(other.getQuery())) return false;
    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (getResultPerPage()
        != other.getResultPerPage()) return false;
    if (corpus_ != other.corpus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getQuery().hashCode();
    hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPageNumber();
    hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResultPerPage();
    hash = (37 * hash) + CORPUS_FIELD_NUMBER;
    hash = (53 * hash) + corpus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.levi.yoon.proto.SearchRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.levi.yoon.proto.SearchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.levi.yoon.proto.SearchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.levi.yoon.proto.SearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.levi.yoon.proto.SearchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *검색 요청을 위한 요청 객체를 표현하는 message 정의
   * </pre>
   *
   * Protobuf type {@code grpc.sample.SearchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.sample.SearchRequest)
      com.levi.yoon.proto.SearchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.levi.yoon.proto.SearchProto.internal_static_grpc_sample_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.levi.yoon.proto.SearchProto.internal_static_grpc_sample_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.levi.yoon.proto.SearchRequest.class, com.levi.yoon.proto.SearchRequest.Builder.class);
    }

    // Construct using com.levi.yoon.proto.SearchRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      query_ = "";

      pageNumber_ = 0;

      resultPerPage_ = 0;

      corpus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.levi.yoon.proto.SearchProto.internal_static_grpc_sample_SearchRequest_descriptor;
    }

    @java.lang.Override
    public com.levi.yoon.proto.SearchRequest getDefaultInstanceForType() {
      return com.levi.yoon.proto.SearchRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.levi.yoon.proto.SearchRequest build() {
      com.levi.yoon.proto.SearchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.levi.yoon.proto.SearchRequest buildPartial() {
      com.levi.yoon.proto.SearchRequest result = new com.levi.yoon.proto.SearchRequest(this);
      result.query_ = query_;
      result.pageNumber_ = pageNumber_;
      result.resultPerPage_ = resultPerPage_;
      result.corpus_ = corpus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.levi.yoon.proto.SearchRequest) {
        return mergeFrom((com.levi.yoon.proto.SearchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.levi.yoon.proto.SearchRequest other) {
      if (other == com.levi.yoon.proto.SearchRequest.getDefaultInstance()) return this;
      if (!other.getQuery().isEmpty()) {
        query_ = other.query_;
        onChanged();
      }
      if (other.getPageNumber() != 0) {
        setPageNumber(other.getPageNumber());
      }
      if (other.getResultPerPage() != 0) {
        setResultPerPage(other.getResultPerPage());
      }
      if (other.corpus_ != 0) {
        setCorpusValue(other.getCorpusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.levi.yoon.proto.SearchRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.levi.yoon.proto.SearchRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object query_ = "";
    /**
     * <pre>
     *쿼리 문자열
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *쿼리 문자열
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *쿼리 문자열
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      query_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *쿼리 문자열
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      
      query_ = getDefaultInstance().getQuery();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *쿼리 문자열
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      query_ = value;
      onChanged();
      return this;
    }

    private int pageNumber_ ;
    /**
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    public int getPageNumber() {
      return pageNumber_;
    }
    /**
     * <code>int32 page_number = 2;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(int value) {
      
      pageNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      
      pageNumber_ = 0;
      onChanged();
      return this;
    }

    private int resultPerPage_ ;
    /**
     * <code>int32 result_per_page = 3;</code>
     * @return The resultPerPage.
     */
    public int getResultPerPage() {
      return resultPerPage_;
    }
    /**
     * <code>int32 result_per_page = 3;</code>
     * @param value The resultPerPage to set.
     * @return This builder for chaining.
     */
    public Builder setResultPerPage(int value) {
      
      resultPerPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 result_per_page = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultPerPage() {
      
      resultPerPage_ = 0;
      onChanged();
      return this;
    }

    private int corpus_ = 0;
    /**
     * <code>.grpc.sample.Corpus corpus = 4;</code>
     * @return The enum numeric value on the wire for corpus.
     */
    public int getCorpusValue() {
      return corpus_;
    }
    /**
     * <code>.grpc.sample.Corpus corpus = 4;</code>
     * @param value The enum numeric value on the wire for corpus to set.
     * @return This builder for chaining.
     */
    public Builder setCorpusValue(int value) {
      corpus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.sample.Corpus corpus = 4;</code>
     * @return The corpus.
     */
    public com.levi.yoon.proto.Corpus getCorpus() {
      @SuppressWarnings("deprecation")
      com.levi.yoon.proto.Corpus result = com.levi.yoon.proto.Corpus.valueOf(corpus_);
      return result == null ? com.levi.yoon.proto.Corpus.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.sample.Corpus corpus = 4;</code>
     * @param value The corpus to set.
     * @return This builder for chaining.
     */
    public Builder setCorpus(com.levi.yoon.proto.Corpus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      corpus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.sample.Corpus corpus = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorpus() {
      
      corpus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.sample.SearchRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.sample.SearchRequest)
  private static final com.levi.yoon.proto.SearchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.levi.yoon.proto.SearchRequest();
  }

  public static com.levi.yoon.proto.SearchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchRequest>
      PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
    @java.lang.Override
    public SearchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.levi.yoon.proto.SearchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

